config/routes.rb
Rails.application.routes.draw do


  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/contact'=> 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/men' => 'static_pages#men'
  get '/women' => 'static_pages#women'
  get '/howtobuy' => 'static_pages#howtobuy'
  get '/material' => 'static_pages#material'

  get '/shipping_payment' => 'static_pages#shipping_payment'
  get '/adminka' => 'static_pages#adminka'
  get '/women_t_shirts' => 'static_pages#women_t_shirts'
  get '/womens_underwear' => 'static_pages#womens_underwear'

  root  'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def men
  end

  def women
  end

  def howtobuy
  end

  def shipping_payment
  end

  def adminka
  end

  def womens_underwear
  end

  def women_t_shirts
  end

  def termsofexchange
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    {
        success:"alert-success",
        error:"alert-danger",
        danger:"alert-danger",
        alert:"alert-warning",
        notice:"alert-info"
    }[name.to_sym] || name
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--<title>TimeOfRecruiting</title>-->
  <title>Ievtushenko Production</title>
  <%= csrf_meta_tags %>
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag 'Logo_I_ico.ico' %> <!--тут лежить логотип для страницы для вкладки-->

</head>
<!--##############################---Search--#############################################-->
<body>
<header>
  <div class="header-top">
    <%= link_to(image_tag("Logo_I.png", size: "75x75",
                          :alt => "rss feed", id:'ievtushenko_logo'), root_path) %><!--тут ссылка на картинку-->
    <p style="line-height: 25px; font-size: 25px; margin:auto">Оптовый и розничный магазин TUW нижнего белья для всей семьи.</p>
  </div>
  <div class="menu" id="top_nav">
    <ul>
      <li><%= link_to "Главная",    home_path %></li>
      <li><%= link_to "О НАС",    about_path %></li>
      <li><%= link_to "Мужское",    men_path %></li>
      <li>
        <a href="#">Женское</a>
        <ul class="submenu">
          <li><%= link_to "Майки",    women_t_shirts_path %></li>
          <li><%= link_to "Пижамы",    women_path %></li>
          <li><%= link_to "Трусики",    womens_underwear_path %></li>
        </ul>
      </li>
      <li>
        <a href="#">Сервис</a>
        <ul class="submenu">
          <li><%= link_to "Как Купить?",    howtobuy_path %></li>
          <li><%= link_to "Вопросы и Ответы",    help_path %></li>
        </ul>
      </li>
      <li><%= link_to "Оплата и Доставка",    shipping_payment_path %>
      </li>
      <li><%= link_to "Контакты",    contact_path %></li>
    </ul>
  </div>
</header>
<%= yield %>
<%#= render 'layouts/footer' %>
</body>
<script src="assets/slick.min.js" type="text/javascript"></script>
<script src="assets/jquery.fancybox.js" type="text/javascript"></script>
<script src="assets/script.js" type="text/javascript"></script>
</html>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html>
<header>
  <style>
    .about_us{
      padding-left: 90px;
      padding-right: 90px;
      font-family: "PT Sans";
      margin: 10px 0 0 0;
      text-align: justify;
    }
  </style>
</header>
<body>
<div class="about_us">
  <h1>О Нас</h1>

  <br>
  <!--<button style="background-position:center; position: center", class="with-delay">-->
  <!--<%#= link_to 'Назад', :back, class: "btn btn-mini btn-info", type: "button" %>-->
  <!--</button>-->

  <div class="about_us">
    <p> Мы предлагает высококачественное бельё известных турецких брендов, таких как  Berrak, Pink secret , и др.</p>
    <p> Эти компании известны тем, кто любит простую, стильную и удобную одежду. Фирмы по производству белья находится в Стамбуле.</p>
    <p> Сырьё для изготовления отличается высоким качеством. Для работы отбирается только высококачественный хлопок, который чешется модальными гребенками. Это дает возможность сделать текстиль мягким и нежным на ощупь.
      в качестве красителей используются натуральные компоненты. Все синтетические карсители имеют сертификаты качества и соответствуют стандартам безопасности.
      Дизайн домашней одежды разрабатывается с учетом с учетом нескольких факторов – простота, стиль и следование модным тенденциям.</p>
    <p> Приемлемые цены на весь представленный в каталоге ассортимент - это следствие поставок товаров напрямую с фабрики изготовителей.</p>
    <p> Если Вам нужно красивое бельё высокого качества от проверенных брендов, обращайтесь к нам - и вы получите отличную продукцию в кратчайшие сроки на выгодных для Вас условиях.</p>
    <p>Желаем Вам приятных и удачных покупок.</p>
  </div>
</div>
</body>
</html>

app/views/static_pages/adminka.html.erb
<h1>StaticPages#adminka</h1>
<p>Find me in app/views/static_pages/adminka.html.erb</p>

app/views/static_pages/contact.html.erb
<!DOCTYPE html>
<html>
<header>
  <style>
    .about_us{
      padding-left: 90px;
      padding-right: 90px;
      font-family: "PT Sans";
      margin: 10px 0 0 0;
      text-align: justify;
    }
  </style>
</header>
<body>
<div class="about_us">
  <h1>Наши Контакты</h1>

  <div class="about_us">

    <h3>Где нас можно найти?</h3><br>
    <p>Г. Одесса, промрынок "7 км", ул Престижная, 455.</p>
    <h3 style="text-align: center;">+38(095) 067-48-23</h3><br>
    <h1 style="text-align: center;">Александр</h1>
    <br><br>
  </div>
</div>
<div id="googlemaps" style="width-max:1920px;wid-min:600; height:500px;background:yellow; position: center"></div>

<script src="js/jquery.js" type="text/javascript"></script>
<script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBN_BcT9zj8l80ABl1GIrJ8jZM1zESf9hk&callback=initMap">
</script>
</body>
</html>

app/views/static_pages/help.html.erb
<!DOCTYPE html>
<html>
<header>
  <style>
    .about_us{
      padding-left: 90px;
      padding-right: 90px;
      font-family: "PT Sans";
      margin: 10px 0 0 0;
      text-align: justify;
    }
  </style>
</header>
<body>
<div class="about_us">

  <h1>Вопросы и ответы</h1>

  <div class="about_us">
    <p>
      На этой странице будут размещаться вопросы и ответы для наших посетителей
    </p>

  </div >
</div>
</body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Ievtushenko Production | <%= yield(:title) %></title>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    .carousel-inner > .item > img,
    .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
    }
    a:hover {
      /*color: #ef5f96;*/
    }
    .about_us{
      padding-left: 90px;
      padding-right: 90px;
      font-family: "PT Sans";
      /*margin: 10px 0 0 0;*/
      text-align: justify;
    }
  </style>
</head>


<body>


<!--Слайдер///////////////////////////////////////-->
<br> <br><br><br>
<div class="slider">
  <div class="slide">
    <img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Carousel/Home_image1.png" alt="slide1">
  </div>
  <div class="slide">
    <img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Carousel/Home_image2.png" alt="slide2">
  </div>
  <div class="slide">
    <img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Carousel/Home_image3.png" alt="slide3">
  </div>
  <div class="slide">
    <img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Carousel/Home_image4.png" alt="slide4">
  </div>
</div>




<!--Мужское и Женское///////////////////////////////////////-->
<!--Женские Пижамы///-->
<br> <br>
<div class="about_us">

  <h1><%= link_to "Женские Пижамы", women_path, id: "schlafanzug"%></h1>
  <br>
  <div class="catalog">
    <div class="women_underwear">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Pigiama/Pigiama_gimp_out_label.png" data-fancybox="gallery" data-fancybox data-caption="Цена - 330грн<br> code: 3001
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Pigiama/Pigiama_gimp_out_label.png" alt="photo"/></a>
      <h3>330 грн</h3>
      <h4>code: 3001</h4>
    </div>
    <div class="women_underwear">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Pigiama/Pigiama2_gimp_out_label.png" data-fancybox="gallery"data-fancybox data-caption="Цена - 330грн<br> code: 3002
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Pigiama/Pigiama2_gimp_out_label.png" alt="photo"/></a>
      <h3>330 грн</h3>
      <h4>code: 3002</h4>
    </div>
    <div class="women_underwear">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Pigiama/Pigiama3_gimp_out_label.png" data-fancybox="gallery" data-fancybox data-caption="Цена - 330грн<br> code: 3003
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Pigiama/Pigiama3_gimp_out_label.png" alt="photo"/></a>
      <h3>330 грн</h3>
      <h4>code: 3003</h4>
    </div>
    <div class="women_underwear">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Pigiama/Pigiama4_gimp_out_label.png" data-fancybox="gallery" data-fancybox data-caption="Цена - 390грн<br> code: 3025
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Pigiama/Pigiama4_gimp_out_label.png" alt="photo"/></a>
      <h3>390 грн</h3>
      <h4>code: 3025</h4>
    </div>

  </div>


  <!--Женские Майки///-->
  <br> <br>

  <h1><%= link_to "Женские Майки", women_t_shirts_path, id: "t_shirts" %></h1>
  <br>
  <div class="catalog">
    <div class="women_t_shirts">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_t_shirts/female_T-shirt1_2011_white_S_M_L_XL_80__2XXL_85grn.png" data-fancybox="gallery" data-fancybox data-caption="
    На Белый Цвет и На Размеры: S-M-L-XL -> Цена - 85грн
    <br>
    На Белый Цвет и На Размер: 2XXL -> Цена - 85грн
    <br>
    code: 2011
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_t_shirts/female_T-shirt1_2011_white_S_M_L_XL_80__2XXL_85grn.png" alt="photo"/></a>
      <h3>80 грн</h3>
      <h4>code: 2011</h4>
    </div>

    <div class="women_t_shirts">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_t_shirts/female_T-shirt1_2015_burgundy_S_M_L_XL_90__Red_80__Pink_90grn.png" data-fancybox="gallery" data-fancybox data-caption="
    На Красный Цвет и На Размеры: S-M-L-XL -> Цена - 80грн
    <br>
    На Бордовый и Розовые Цвета и На Размеры: S-M-L-XL -> Цена - 90грн
    <br>
    code: 2015
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_t_shirts/female_T-shirt1_2015_burgundy_S_M_L_XL_90__Red_80__Pink_90grn.png" alt="photo"/></a>
      <h3>80 грн</h3>
      <h4>code: 2015</h4>
    </div>

    <div class="women_t_shirts">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_t_shirts/female_T-shirt_grey_8049_S_M_L_XL_64grn.png" data-fancybox="gallery" data-fancybox data-caption="
    На Серый Цвет и на Размеры: S-M-L-XL -> Цена - 64грн
    <br>
    code: 8049
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_t_shirts/female_T-shirt_grey_8049_S_M_L_XL_64grn.png" alt="photo"/></a>
      <h3>64 грн</h3>
      <h4>code: 8049</h4>
    </div>


    <div class="women_t_shirts">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_t_shirts/female_T-shirt1_2118_Black_Beige_S_M_L_XL_85grn.png" data-fancybox="gallery" data-fancybox data-caption="
    На Черный и Бежевые Цвета и На Размеры: S-M-L-XL -> Цена - 85грн
    <br>
    code: 2118
    "><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_t_shirts/female_T-shirt1_2118_Black_Beige_S_M_L_XL_85grn.png" alt="photo"/></a>
      <h3>85 грн</h3>
      <h4>code: 2118</h4>
    </div>

  </div>

  <!--Мужское белье///-->
  <br> <br>
  <h1><%= link_to "Мужское белье", men_path %></h1>
  <br>
  <div class="catalog">
    <div class="men_underwear">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Men_underwear/Men1_underwear_4476_black_Dark%20blue_Burgundy_rose_Purple_Bright%20blue__Gray_Dark%20blue_85grn.png" data-fancybox="gallery" data-fancybox data-caption="
    Цена - 85грн на цвета: Черный, Темно-синий, Бордовый, Роза, Фиолетовый, Ярко-синий, Серый, Тёмно-синий <br> code: 4476
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Men_underwear/Men1_underwear_4476_black_Dark%20blue_Burgundy_rose_Purple_Bright%20blue__Gray_Dark%20blue_85grn.png" alt="photo"/></a>
      <h3>85 грн</h3>
      <h4>code: 4476</h4>
    </div>
    <div class="men_underwear">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Men_underwear/Men2_underwear_4480_standart_80grn.png" data-fancybox="gallery" data-fancybox data-caption="
     Цена - 80грн, цвет: стандартный<br> code: 4480
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Men_underwear/Men2_underwear_4480_standart_80grn.png" alt="photo"/></a>
      <h3>80 грн</h3>
      <h4>code: 4480</h4>
    </div>
    <div class="men_underwear">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Men_underwear/Men_underwear_4413_standart_120grn.png" data-fancybox="gallery" data-fancybox data-caption="
    Цена - 80грн, цвет: стандартный<br> code: 4480
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Men_underwear/Men_underwear_4413_standart_120grn.png" alt="photo"/></a>
      <h3>120 грн</h3>
      <h4>code: 4413</h4>
    </div>
    <div class="men_underwear">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Men_underwear/Men_underwear_dark_grey_1084_S_M_L_XL_100grn.png" data-fancybox="gallery" data-fancybox data-caption="
    На Темно-Серый Цвет и на Размеры: S-M-L-XL -> Цена - 120грн
    <br>
    code: 1084
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Men_underwear/Men_underwear_dark_grey_1084_S_M_L_XL_100grn.png" alt="photo"/></a>
      <h3>120 грн</h3>
      <h4>code: 1084</h4>
    </div>
  </div>
  <br>


  <!--Мужское белье///-->
  <br> <br>
  <h1><%= link_to "Женское Белье", womens_underwear_path %></h1>
  <br>
  <div class="catalog">
    <div class="men_underwear">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_underwear/Women_underwear_11255_25grn.png" data-fancybox="gallery" data-fancybox data-caption="
    На Размеры: L-M -> Цена - 25грн
    <br>
    code: 11255
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_underwear/Women_underwear_11255_25grn.png" alt="photo"/></a>
      <h3>25 грн</h3>
      <h4>code: 11255</h4>
    </div>

    <div class="men_underwear">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_underwear/Women_underwear_11257_L_M_35grn.png" data-fancybox="gallery" data-fancybox data-caption="
    На Размеры: L-M -> Цена - 35грн
    <br>
    code: 11257
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_underwear/Women_underwear_11257_L_M_35grn.png" alt="photo"/></a>
      <h3>35 грн</h3>
      <h4>code: 11257</h4>
    </div>

    <div class="men_underwear">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_underwear/Women_underwear_11258_L_M_35grn.png" data-fancybox="gallery" data-fancybox data-caption="
    На Размеры: L-M -> Цена - 35грн
    <br>
    code: 11258
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_underwear/Women_underwear_11258_L_M_35grn.png" alt="photo"/></a>
      <h3>35 грн</h3>
      <h4>code: 11258</h4>
    </div>

    <div class="men_underwear">
      <a href="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_underwear/Women_underwear_11259_S_M_L_XL_40grn.png" data-fancybox="gallery" data-fancybox data-caption="
    На Размеры: S-M-L-XL -> Цена - 40грн
    <br>
    code: 11259
			"><img src="https://s3.eu-central-1.amazonaws.com/ievtushenko/Women_underwear/Women_underwear_11259_S_M_L_XL_40grn.png" alt="photo"/></a>
      <h3>40 грн</h3>
      <h4>code: 11259</h4>
    </div>
  </div>
</div>
<!--Footer///////////////////////////////////////////////////////////-->


<footer>
  <div class="service">
    <h3>Где нас можно найти?</h3>
    <p>Г. Одесса, промрынок "7 км", ул Престижная, 455.</p>
    <p>Ассортимент на сайте может отличаться от фактического.</p>
    <br><br><br><br>

  </div>
  <div class="contacts">
    <h3>Контакты</h3>
    <h3>+38(095) 067-48-23</h3>
    <h1 style="color:whitesmoke">Александр</h1>

    <h3>Поделиться</h3>
    <a href="https://www.facebook.com/Underwear-196240304295770/"><img src="assets/facebook.png" alt="facebook"></a>
    <a href="https://www.instagram.com/underwear_for_her_and_him/"><img src="assets/instagram.png" alt="instagram"></a>
    <hr>
    <h3 class="tesl_n_co"><%= link_to "Tesl-N-Co Development", "https://www.facebook.com/akvelibrium", id: "tesl_n_co" %></h3>

  </div>
  <div class="timework">
    <h3>Время работы</h3>
    <p>ПН: 10:00 - 17:00</p>
    <p>ВТ: 10:00 - 17:00</p>
    <p>СР: 10:00 - 17:00</p>
    <p>ЧТ: 10:00 - 17:00</p>
    <p>ПТ: Выходной</p>
    <p>СБ: 10:00 - 17:00</p>
    <p>ВС: 10:00 - 17:00</p>
  </div>
</footer>
<script src="assets/jquery.js" type="text/javascript"></script>
<script src="assets/slick.min.js" type="text/javascript"></script>
<script src="assets/jquery.fancybox.js" type="text/javascript"></script>
<script src="assets/script.js" type="text/javascript"></script>
</body>
</html>

app/views/static_pages/howtobuy.html.erb
<!DOCTYPE html>
<html>
<header>
  <style>
    .about_us{
      padding-left: 90px;
      padding-right: 90px;
      font-family: "PT Sans";
      margin: 10px 0 0 0;
      text-align: justify;
    }
  </style>
</header>
<body>

<div class="about_us">
  <h1>Как купить нашу продукцию?</h1>

  <div class="about_us">
    <p>Для того, чтобы сделать заказ в нашем интернет-магазине, достаточно связаться с нами по указанным на сайте телефонам.</p>
    <p>Оплата осуществляется наложенным платежом или через начисления денег на карту Приватбанка</p>
  </div>
</div>
</body>
</html>

app/views/static_pages/shipping_payment.html.erb
<html>
<header>
  <style>
    .about_us{
      padding-left: 90px;
      padding-right: 90px;
      font-family: "PT Sans";
      margin: 10px 0 0 0;
      text-align: justify;
    }
  </style>
</header>
<body>

<div class="about_us">
  <h1>Оплата и Доставка</h1>

  <div class="about_us">
    <p>Интернет-магазин "https://ievtushenko.herokuapp.com" осуществляет доставку товарв по всей Украине.</p>
    <p>
      Для того, чтобы сделать заказ в нашем интернет-магазине, достаточно заполнить форму онлайн-заказа или связаться с менеджерами по указанным на сайте телефонам.
    </p>
    <br>

    <h3 style="text-align: center;">Условия доставки по Украине.</h3>
    <br>
    <p>Доставка товаров по Украине осуществляется в течении 1-2 дней, через отделения Новой почты, Укрпочты, Интайм, Деливери, и т д. Узнать точное время и условия доставки в ваш город, вы можете у оператора нашего контакт-центра.</p>
  </div>
</div>
</body>
</html>